CREATE TABLE tbl_user (
	idx INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL,
	id VARCHAR(255) NOT null,
	pw VARCHAR(255) NOT NULL,
	sex CHAR(1) NOT NULL,
	birth DATE NOT NULL,
	agree CHAR(1) NOT NULL,
	r_date DATETIME DEFAULT CURRENT_TIMESTAMP,
	m_date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE current_timestamp
);