CREATE TABLE tbl_board (
	idx INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	user_id VARCHAR(255) NOT null,
	title VARCHAR(255) NOT NULL,
	content VARCHAR(1000) NOT NULL,
	r_date DATETIME DEFAULT CURRENT_TIMESTAMP,
	m_date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE current_timestamp
);